### ISSUE TITLE
Vanilla Animals Expanded

### ISSUE THREAD

**Issue by Draconomial** [emipa606/DogsMate#1]
Vanilla Animals Expanded were all merged into one mod, breaking compatibility.

**Comment by emipa606** [comment]
Should be fixed now, changed it to conditional patches instead
Published with 7b444e5

**Comment by Draconomial** [comment]
Fucking hell. I submit this issue 47 minutes ago. Spend 40 minutes fixing it myself so that I can push it to your git, only to find that you noticed and fixed it 20 minutes ago. You're a machine.
